### ISSUE TITLE
Created Simple TDD

### ISSUE THREAD

**Issue by PonceER** [PonceER/WebCalculator#1]
Created simple test cases for the web calc. 
Please see:  Go School - Microservices 2 - Activity3.xlsx
Would you like to create a simple Add test case? Then I'll write the Add function code based on that (so we can show a few ding-dong for TDD).
Thanks!

**Comment by gavinerh83** [comment]
ok i'll create the test case, using the testify library package

**Comment by PonceER** [comment]
@gavinerh83
Created .github/workflows/GroupGoSetup.yml for build testing.
Created calc.go with Add function.

The Add function passed from your test case script using testify:
https://github.com/PonceER/WebCalculator/runs/1470485917

Let us proceed with the Subtract test case. Thanks.

**Comment by PonceER** [comment]
@gavinerh83
The Subtract function passed:
https://github.com/PonceER/WebCalculator/runs/1471895315?check_suite_focus=true

Let us proceed with the Multiply test case. Thanks.

**Comment by PonceER** [comment]
@gavinerh83
The Multiply function passed:
https://github.com/PonceER/WebCalculator/runs/1496341108?check_suite_focus=true

Let us proceed with the final test case (i.e. Divide). Thanks.

**Comment by gavinerh83** [comment]
Ok, just added the divide test

**Comment by PonceER** [comment]
The Divide (with divide by 0) function passed:
https://github.com/PonceER/WebCalculator/actions/runs/399809735

--- TDD simulation completed ---
